extends Resource
class_name BarrelDataResource

## Keep adding new item at the bottom, dont add at the middle of list
enum BarrelIdEnum {
	NONE,
	TEST,
	ARCHETYPE,
	DYNAMIC_ADVANTAGE,
	FOOL_ROLLER,
	PROJECTILE_COUNT,
	TRICKSHOT,
	ARCHETYPE_SHOTGUN_SPEC,
	ROULETTE_BOSS,
	ARCHETYPE_RAILGUN_SPEC,
	ARCHETYPE_AUTOMATIC_SPEC,
	PIT_BOSS_BARREL,
	BARTENDER_BOSS_BARREL,
	DELAYED_GRATIFICATION,

	DEBUG_ARCHETYPE_RAILGUN,
	DEBUG_ARCHETYPE_SMG,
	DEBUG_ARCHETYPE_SHOTGUN,
	DEBUG_AMMO_LEECH,
	DEBUG_DOUBLE_TAP,
	DEBUG_EXPLOSIVE_BULLET,
	DEBUG_EXTENDED_DRUM,
	DEBUG_GAMBLERS_PRECISION,
	DEBUG_RAMP_UP,
	DEBUG_BULLET_TIME,
	DEBUG_STICKY_BOMB,
	DEBUG_MEDICAL_PAYOUT,
	DEBUG_BALL_BULLET,
	DEBUG_NEWTONS_THIRD,
	DEBUG_SHIELD,
	DEBUG_HOMING_BULLETS,
	DEBUG_RICOCHET,
	DEBUG_HYPERFOCUS,
	DEBUG_DEATH_FROM_ABOVE,
	DEBUG_EMPOWERED_DASH,
	DEBUG_FORTITUDE,
	DEBUG_TAG_AND_SHRED,
	DEBUG_MOLOTOV_DASH,
	DEBUG_TOXIN_MIST,
	DEBUG_COGNAC_RELOAD,

	ACHETYPE_GELTHROWER_SPEC,
	PLACEHOLDER_BARREL_A,
	PLACEHOLDER_BARREL_B,
	PLACEHOLDER_BARREL_C,
	RECKLESS_ABANDON,
	LEG_EYE_COORDINATE,
	KINEMATIC_EQUATION,
	ELEMENTAL_INFUSION
}

@export var barrel_id: BarrelIdEnum
@export var barrel_name: String
@export_multiline var barrel_desc: String
@export var barrel_image: Texture2D
@export var barrel_cost: int = 200
@export var barrel_prefab: PackedScene
@export var is_archetype_barrel: bool = false
