extends Resource
class_name BarrelDataResource

## Keep adding new item at the bottom, dont add at the middle of list
enum BarrelIdEnum {
	NONE,
	TEST,
	ARCHETYPE,
	DYNAMIC_ADVANTAGE,
	FOOL_ROLLER,
	PROJECTILE_COUNT,
	TRICKSHOT,
	ARCHETYPE_SHOTGUN_SPEC,
	ROULETTE_BOSS,
	ARCHETYPE_RAILGUN_SPEC,
	ARCHETYPE_AUTOMATIC_SPEC,
	PIT_BOSS_BARREL,
	BARTENDER_BOSS_BARREL,
	DELAYED_GRATIFICATION,

	DEBUG_RAILGUN,
	DEBUG_SMG,
	DEBUG_SHOTGUN,
	DEBUG_AMMO_LEECH,
	DEBUG_DOUBLE_TAP,
	DEBUG_EXPLOSIVE_BULLET,
	DEBUG_EXTENDED_DRUM,
	DEBUG_GAMBLERS_PRECISION,
	DEBUG_RAMP_UP,
	DEBUG_BULLET_TIME,
	DEBUG_STICKY_BOMB,
	DEBUG_MEDICAL_PAYOUT,
	DEBUG_BALL_BULLET,
	DEBUG_NEWTON_THIRD_LAW,
	DEBUG_SHIELD,
	DEBUG_HOMING,
	DEBUG_RICOCHET,
	DEBUG_HYPERFOCUS,
	DEBUG_DEATH_FROM_ABOVE,
	DEBUG_EMPOWERED_DASH,
	DEBUG_FORTITUDE,
	DEBUG_TAG_AND_SHRED,
	DEBUG_MOLOTOV_DASH,
	DEBUG_TOXIN_MIST,
	DEBUG_COGNAC_RELOAD,

	ACHETYPE_GELTHROWER_SPEC,
	PLACEHOLDER_BARREL_A,
	PLACEHOLDER_BARREL_B,
	PLACEHOLDER_BARREL_C,
	RECKLESS_ABANDON,
	LEG_EYE_COORDINATE,
	KINEMATIC_EQUATION,
	ELEMENTAL_INFUSION,
	
	DEBUG_GEL_BLOB,
	DEBUG_GEL_BUBBLE,
	DEBUG_GEL_STREAM,
	DEBUG_COLD_INFUSION,
	DEBUG_ELECTRIC_INFUSION,
	DEBUG_FIRE_INFUSION,
	DEBUG_POISON_INFUSION,
	DEBUG_EXECUTIONER_ROUND,
	DEBUG_FLEXIBLE_KNEE,
	DEBUG_GLASS_CANNON,
	DEBUG_LONG_SHOT,
	DEBUG_REACTIVE_SHOT,
	DEBUG_SLOW_ROLLER,
	DEBUG_SNAP_CALL,
	DEBUG_SPLIT,
	DEBUG_SPRINGY_FEET,
	DEBUG_TRIGGER_LEG,
	DEBUG_COMBAT_SHOTGUN,
	DEBUG_DOUBLE_BARREL,
	DEBUG_SLUG,
	DEBUG_GAUSS_RIFLE,
	DEBUG_SCATTER_BEAM,
	DEBUG_RAILCANNON,
	DEBUG_AMERICAN_RIFLE,
	DEBUG_RUSSIAN_RIFLE,
	DEBUG_LMG,
	DEBUG_VECTOR,

	BLACKJACK
}

@export var barrel_id: BarrelIdEnum
@export var barrel_name: String
@export_multiline var barrel_desc: String
@export_multiline var barrel_info_summary: String
@export var barrel_image: Texture2D
@export var barrel_cost: int = 200
@export var barrel_prefab: PackedScene
@export var is_archetype_barrel: bool = false